# Paths
PREPROCESSED_DATA_DIR: "/work/FAC/FGSE/IDYST/tbeucler/downscaling/fquareng/data/extremes/OPERA/patches/precip"
# PREPROCESSED_DATA_DIR: "/home/fquareng/work/data/"
DEM_DATA_DIR: "/work/FAC/FGSE/IDYST/tbeucler/downscaling/fquareng/data/extremes/OPERA/patches/dem"
DEM_STATS: "/work/FAC/FGSE/IDYST/tbeucler/downscaling/fquareng/data/extremes/OPERA/patches/dem/dem_stats.json"

TRAIN_METADATA_FILE: "/work/FAC/FGSE/IDYST/tbeucler/downscaling/fquareng/data/extremes/OPERA/train_patches_metadata.txt"
# TRAIN_METADATA_FILE: "/home/fquareng/work/data/train_patches_metadata.txt"
VAL_METADATA_FILE: "/work/FAC/FGSE/IDYST/tbeucler/downscaling/fquareng/data/extremes/OPERA/val_patches_metadata.txt"
# VAL_METADATA_FILE: "/home/fquareng/work/data/val_patches_metadata.txt"
TEST_METADATA_FILE: "/work/FAC/FGSE/IDYST/tbeucler/downscaling/fquareng/data/extremes/OPERA/test_patches_metadata.txt"
# TEST_METADATA_FILE: "/home/fquareng/work/data/test_patches_metadata.txt"

# Precipitation patches
PRECIP_VAR_NAME: "TOT_PREC"
PATCH_SIZE: 128
DOWNSCALING_FACTOR: 6
PIXEL_SIZE_KM: 2.0 # Size of one high-res pixel in km
PERSISTENCE_THRESHOLD: 0.01 # Persistence threshold for topological simplification

ANALYSIS_DATA_PERCENTAGE: 100 # Use 100% of the data. Change to 50 for 50%, etc.

# Ratios for splitting the dataset. Must sum to 1.0.
SPLIT_RATIOS:
  train: 0.8
  validation: 0.1
  test: 0.1

# DataLoaders
NUM_WORKERS: 16
BATCH_SIZE: 32
BATCH_COMPOSITION:
  "dry": 0.33
  "normal": 0.33
  "extreme": 0.33

# Training
EXPERIMENT_NAME: "GammaEmulatorv2"
HARD_CONSTRAINED: false
LOSS_LAMBDA: 0.25 # between 0 and 1 (Loss = lambda*zero_penalty + (1-lambda)*main_loss)
LAMBDA_BOUND: 0.25 # between 0 and 1 (Loss = (1-lambda)*main_loss + lambda*bound_penalty)
SUBSAMPLE_FRACTION: 1
device: "cuda"
NUM_EPOCHS: 100
PATIENCE: 10
EARLY_STOPPING: true
EARLY_STOPPING_PATIENCE: 10
EARLY_STOPPING_DELTA: 0.001
LEARNING_RATE: 0.0001
QUANTILE_LEVELS: [
  0.01,
  0.05,
  0.1,
  0.25,
  0.5,
  0.75,
  0.9,
  0.95,
  0.99,
]

USE_SURROGATE_LOSS: false
SURROGATE_LOSS_WEIGHT: 0.25 # Weight of the surrogate loss when USE_SURROGATE_LOSS is true (between 0 and 1)
EMULATOR_CHECKPOINT_PATH: "/work/FAC/FGSE/IDYST/tbeucler/downscaling/fquareng/ExtremePrecipSR/models/gamma_emulator_v2/best_model.pth"
EMULATOR_IS_HARD_CONSTRAINED: true