# Paths
RAW_OPERA_DATA_DIR: "/work/FAC/FGSE/IDYST/tbeucler/downscaling/raw_data/OPERA"
METADATA_DIR: "/work/FAC/FGSE/IDYST/tbeucler/downscaling/fquareng/data/extremes/OPERA/metadata_v2"
PREPROCESSED_DATA_DIR: "/work/FAC/FGSE/IDYST/tbeucler/downscaling/fquareng/data/extremes/OPERA/patches_v2/precip"

# OLD
# TRAIN_METADATA_FILE: "/work/FAC/FGSE/IDYST/tbeucler/downscaling/fquareng/data/extremes/OPERA/train_patches_metadata.txt"
# VAL_METADATA_FILE: "/work/FAC/FGSE/IDYST/tbeucler/downscaling/fquareng/data/extremes/OPERA/val_patches_metadata.txt"
# TEST_METADATA_FILE: "/work/FAC/FGSE/IDYST/tbeucler/downscaling/fquareng/data/extremes/OPERA/test_patches_metadata.txt"
# DEM_PATCH_DIR: "/work/FAC/FGSE/IDYST/tbeucler/downscaling/fquareng/data/extremes/OPERA/patches/dem"
# EXPERIEMENTS_DIR: "/scratch/fquareng/experiments_2"

# Precipitation patches
PRECIP_VAR_NAME: "TOT_PREC"
PATCH_SIZE: 128
DOWNSCALING_FACTOR: 6
DECLUTTER_THRESHOLD: 150.0

ANALYSIS_DATA_PERCENTAGE: 50 # Use 100% of the data. Change to 50 for 50%, etc.

# Ratios for splitting the dataset. Must sum to 1.0.
SPLIT_RATIOS:
  train: 0.8
  validation: 0.1
  test: 0.1

# DataLoaders
BATCH_SIZE: 32
MAX_WORKERS: 8
NUM_WORKERS: 0

# UNet
DROPOUT_PROB: 0.3

# S_INV
S_ESTIMATION_SAMPLES: 10000

# Training
SUBSAMPLE_FRACTION: 1
device: "cuda"
NUM_EPOCHS: 100
PATIENCE: 10
EARLY_STOPPING: true
EARLY_STOPPING_PATIENCE: 5
LEARNING_RATE: 0.00001
QUANTILE_LEVELS: [
    0.01,
    0.05,
    0.1,
    0.25,
    0.5,
    0.75,
    0.9,
    0.95,
    0.99,
]