using YAML
using NPZ
using Ripserer  # Use Ripserer.jl for cubical persistence
using Contour
using ProgressMeter
using Printf

# --- Configuration Loading ---
# Adjust this path as needed
const config_path = "/work/FAC/FGSE/IDYST/tbeucler/downscaling/fquareng/ExtremePrecipSR/config.yaml"

const config = YAML.load_file(config_path)
const QUANTILE_LEVELS = config["QUANTILE_LEVELS"]
const PREPROCESSED_DATA_DIR = config["PREPROCESSED_DATA_DIR"]
const PIXEL_SIZE_KM = get(config, "PIXEL_SIZE_KM", 1.0)
const PERSISTENCE_THRESHOLD = get(config, "PERSISTENCE_THRESHOLD", 0.05)
# Use all available threads
const NUM_WORKERS = Threads.nthreads()

# --- TDA and Geometric Functions ---

"""
Computes the persistence diagram once for a given image.
Input is assumed to be cleaned (no NaNs).
"""
function compute_tda_persistence(prec_2d_np_clean::Matrix{Float64})
    # Negate the field for sublevel set persistence
    neg_prec_field = -prec_2d_np_clean
    
    # Compute 0-dimensional persistence of the cubical complex
    # `alg=:cubical` uses the image as a cubical complex.
    # `dim_max=0` computes H_0 (connected components).
    persistence_diagrams = ripserer(neg_prec_field, dim_max=0, alg=:cubical)
    
    # ripserer returns a vector of diagrams, one per dimension.
    return persistence_diagrams[1] # This is the H_0 diagram
end

"""
Filters pre-computed persistence pairs for CC count at a given threshold.
"""
function filter_persistence_for_cc(persistence_diagram, threshold::Float64, persistence_threshold::Float64)
    # persistence_diagram is a Vector{PersistenceInterval} for H_0
    num_features_tda = 0
    
    # Each `interval` in the H_0 diagram is a (birth, death) pair
    # from the *negated* field.
    for interval in persistence_diagram
        birth_val_neg = interval.birth
        death_val_neg = interval.death # This will be Inf for the background component
        
        # Convert back to precipitation values
        birth_prec = -birth_val_neg
        death_prec = (death_val_neg == Inf) ? Inf : -death_val_neg
        
        persistence = (death_prec == Inf) ? Inf : (birth_prec - death_prec)

        # Count if significant and exists at or above the threshold
        if persistence > persistence_threshold && birth_prec >= threshold
            # Exclude the background component unless threshold is very low
            if death_val_neg != Inf
                num_features_tda += 1
            elseif threshold <= 0.01  # Count background only at low thresholds
                num_features_tda += 1
            end
        end
    end
    return num_features_tda
end

"""
Calculates the perimeter from contours generated by Contour.jl.
"""
function calculate_perimeter(contours_obj, pixel_size_km::Float64)
    total_perimeter_pixels = 0.0
    # Contour.lines gives an iterator of contour lines
    for line in Contour.lines(contours_obj)
        xs, ys = line.vertices # Get vertex coordinates
        for i in 1:(length(xs) - 1)
            # Sum Euclidean distance between adjacent points
            dx = xs[i+1] - xs[i]
            dy = ys[i+1] - ys[i]
            total_perimeter_pixels += sqrt(dx^2 + dy^2)
        end
    end
    return total_perimeter_pixels * pixel_size_km
end


"""
Computes Area and Perimeter for a single threshold.
"""
function compute_A_P_single_threshold(prec_2d_np_clean::Matrix{Float64}, threshold::Float64, pixel_size_km::Float64=1.0)
    mask = prec_2d_np_clean .>= threshold
    area_km2 = sum(mask) * (pixel_size_km^2)
    
    # Contour.jl needs axes. We use 1-based pixel coordinates.
    xs = 1:size(mask, 1)
    ys = 1:size(mask, 2)
    
    # Find contours at the 0.5 level
    contours_obj = Contour.contours(xs, ys, Float64.(mask), [0.5])
    perimeter_km = calculate_perimeter(contours_obj, pixel_size_km)
    
    return area_km2, perimeter_km
end

"""
Computes the Gamma matrix, calculating TDA persistence only once.
"""
function compute_gamma_matrix_for_image(
    prec_2d_data::AbstractMatrix,
    thresholds::Vector,
    pixel_size_km::Float64,
    persistence_threshold::Float64,
)
    gamma_matrix = zeros(Float32, 3, length(thresholds))
    
    # Clean NaNs and ensure Float64 for TDA and Contour
    prec_2d_np_clean = map(x -> isnan(x) ? -1.0 : Float64(x), prec_2d_data)

    # --- Compute TDA Persistence ONCE ---
    persistence_diagram_h0 = compute_tda_persistence(prec_2d_np_clean)
    # ------------------------------------

    for (i, threshold_value_any) in enumerate(thresholds)
        threshold_value = Float64(threshold_value_any) # Ensure type
        
        # Calculate Area and Perimeter for this threshold
        area_km2, perimeter_km = compute_A_P_single_threshold(
            prec_2d_np_clean, threshold_value, pixel_size_km
        )

        # Filter pre-computed persistence for CC count at this threshold
        num_features_tda = filter_persistence_for_cc(
            persistence_diagram_h0, threshold_value, persistence_threshold
        )

        gamma_matrix[1, i] = Float32(area_km2)
        gamma_matrix[2, i] = Float32(perimeter_km)
        gamma_matrix[3, i] = Float32(num_features_tda)
    end

    return gamma_matrix
end


# --- Main Processing Function (Multithreaded) ---

"""
Processes a data split in parallel using multithreading.
"""
function process_and_save_gamma_targets(data_split::String)
    println("--- Processing data split: $data_split ---")
    input_dir = joinpath(PREPROCESSED_DATA_DIR, data_split)
    precip_path = joinpath(input_dir, "original_precip.npz")
    output_path = joinpath(input_dir, "gamma_targets_persistence.npz")

    if !isfile(precip_path)
        println("Precipitation file not found: $precip_path. Skipping.")
        return
    end

    println("Loading precipitation data structure from $precip_path...")
    
    # NPZ.npzopen provides a lazy-loaded dictionary-like object (NpyDict).
    npz_handle = npzread(precip_path)
    precip_data = npz_handle["data"] # This is an NpyArray, not an in-memory Array

    num_samples = size(precip_data, 1)
    num_thresholds = length(QUANTILE_LEVELS)
    output_shape = (num_samples, 3, num_thresholds)
    
    println("Allocating output array in RAM: $output_shape")
    gamma_targets_array = Array{Float32}(undef, output_shape)

    println("Computing Gamma matrices for $num_samples samples using $NUM_WORKERS threads...")

    # Initialize thread-safe progress bar
    p = Progress(num_samples)

    # --- Parallel Loop ---
    Threads.@threads for i in 1:num_samples
        # Slicing the NpyArray `precip_data[i, :, :]` performs
        # a disk read for *only* that slice.
        prec_field = precip_data[i, :, :]
        
        gamma_matrix = compute_gamma_matrix_for_image(
            prec_field,
            QUANTILE_LEVELS,
            PIXEL_SIZE_KM,
            PERSISTENCE_THRESHOLD,
        )
        
        # Write result directly to the in-memory array
        gamma_targets_array[i, :, :] = gamma_matrix
        
        next!(p) # Update progress bar
    end
    
    finish!(p)
    close(npz_handle) # Close the npz file handle

    println("All computations finished. Saving compressed Gamma matrices...")
    
    # This MUST be prefixed with `NPZ.` to resolve the UndefVarError
    NPZ.npzwrite(output_path, Dict("data" => gamma_targets_array); compress=true)
    
    println("Saved compressed Gamma matrices to $output_path")
    @printf("Finished processing for %s. Shape of saved data: %s\n", data_split, string(output_shape))
end

"""
Main execution function.
"""
function main()
    if Threads.nthreads() == 1
        @warn "Julia started with 1 thread. " * "For parallel processing, restart Julia with threads: \n" *
              "  julia -t auto precompute_gamma.jl"
    else
        @info "Running with $(Threads.nthreads()) threads."
    end
    
    data_splits = ["train", "validation", "test"]
    for split in data_splits
        process_and_save_gamma_targets(split)
    end
    println("\nAll pre-computation is complete.")
end

# --- Script Entry Point ---
if abspath(PROGRAM_FILE) == @__FILE__
    main()
end